osx_image: xcode8.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - brew install swiftlint
  - gem install cocoapods --pre
  - pod install --project-directory=Example
script:
  - swiftlint
  - set -o pipefail && xcodebuild test -workspace Example/MrThumb.xcworkspace -scheme mrthumb-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
